### ISSUE TITLE
gatsby v4 마이그레이션

### ISSUE THREAD

**Issue by lkoiescg2031** [lkoiescg2031/my-netlify-blog-v4#1]
## AS IS
gatsby v2 https://github.com/lkoiescg2031/my-netlify-blog

## TO BE
gatsby v4, 의존라이브러리 업데이트 필요

## tasks

 - [x] install new gatsby v4
 - migration code 
     - POST
         - [x] 포스트 데이터 이동
         - [x] 코드 이동
         - [x] mui 의존성 업데이트
         - [x] styled-component -> emotion 교체
         - [x] post 각 페이지 요소 랜더 확인
            - 코드 요소, 이미지 등 점검
     - [x] CATEGORY
     - [x] TAGS
     - index 페이지
        - [x] 코드 이동
        - [x] 의존성 업데이트
        - [x] styled-component 교체
     - [x] 404
 - [ ] build and deploy

## logs

 - 라이브러리 변경사항이 많아 새로 작성하는 것이 빠를 것으로 보임
 - https://www.gatsbyjs.com/plugins/gatsby-plugin-material-ui/ mui v5 변경, styled-components 시스템 변경됨
 - mui 의존성 업데이트 후 경로 수정 완료 styled-components 사용하지 않을 것으로 보임 (emotion 라이브러리 확인)
    - https://www.gatsbyjs.com/docs/how-to/styling/emotion/
